#!/usr/bin/expect -f

set timeout 30
set host "37.27.54.247"
set user "nirosha_1"
set password "Celorita13jan!!"
set port "22"

spawn ssh -p $port $user@$host

expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    "$ " {
        send "pwd\r"
        expect "$ "
        send "ls -la\r"
        expect "$ "
        send "exit\r"
    }
    "# " {
        send "pwd\r"
        expect "# "
        send "ls -la\r"
        expect "# "
        send "exit\r"
    }
}

expect eof
